source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'aggregate_root', '~> 2.5.1'
gem 'ruby_event_store', '~> 2.5.1'
gem 'dry-types'
gem 'dry-struct'
gem 'infra', path: '../../infra'

group :development, :test do
	gem 'pry-nav'
  gem 'rspec'
  gem 'rubocop-rails', require: false

  source "https://oss:7AXfeZdAfCqL1PvHm2nvDJO6Zd9UW8IK@gem.mutant.dev" do
    gem "mutant-license"
  end

  source "https://rubygems.org" do
    gem "mutant-rspec"
  end
end

group :test do
  gem 'rspec'
end
