source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'aggregate_root', '~> 2.5.1'
gem 'ruby_event_store', '~> 2.5.1'
gem 'dry-types'
gem 'dry-struct'
gem 'infra', path: '../../infra'

gem 'rom-sql', '~> 3.2'
gem 'pg'
gem 'rake'
gem 'rake'
gem 'dotenv-rails'
gem 'erb'

group :development, :test do
	gem 'pry-nav'
  gem 'rspec'
  gem 'rubocop-rails', require: false
  gem 'database_cleaner-sequel'
end

group :test do
  gem 'rspec'
end
