source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'infra', path: '../../infra'

group :development, :test do
	gem 'pry-nav'
  gem 'rspec'
  gem 'rubocop-rails', require: false
  gem 'database_cleaner-sequel'
end

group :test do
  gem 'rspec'
end

gemspec
