@startuml

package "Infra" {
}

package "Fullfillments" {
  [Order] - OrderCommands
  OrderEvents - [Order]
}


database "RDBMS for Webb App" {
	[DB1]
}

database "RDBMS for Reporting Webb App" {
	[DB2]
}

database "RDBMS for Processes" {
	[DB3]
}

database "RDBMS for Teams" {
	[DB_GDPR_Sensitive_Data]
}

package "Payments" {
  CardEvents - [Card]
  [Card] - CardCommands
}

package "Processes" {
}

package "Teams" {
	MemberEvents -left- [Member]
	[Member] -up- MemberCommands
	TeamEvents -up- [Team]
	[Team] - TeamCommands
}

package "TimeHarvest" {
	TimeEvents - [Account]
	[Account] - TimeCommands
}

package "Web Interface" {
	[Reporting RailsApplication]
	[Main RailsApplication]
}

Fullfillments ---|> Infra
Payments ---|> Infra
Processes ---|> Infra
Processes --|> DB3
Teams ---|> Infra
Teams -|> DB_GDPR_Sensitive_Data
TimeHarvest ---|> Infra

"Main RailsApplication" ----> TimeCommands : issues
"Main RailsApplication" ----> TeamCommands : issues
"Main RailsApplication" ----> MemberCommands : issues
"Main RailsApplication" ----> OrderCommands : issues
"Main RailsApplication" -> DB1
"Reporting RailsApplication" ..> "Main RailsApplication" :consumes remote events
"Reporting RailsApplication" ...> CardEvents :consumes
"Reporting RailsApplication" -> DB2
Processes ..up.> CardEvents :consumes
Processes ..up.> OrderEvents :consumes
Processes ..up.> TeamEvents :consumes
Processes ..up.> TimeEvents :consumes
Processes --up-> CardCommands :issues

@enduml